version: "3.5"

services: 
    go-server:
        build: 
            context: .
            dockerfile: Dockerfile
        image: davidyap/go-1:latest
        container_name: go-server
        ports: 
            - 8080:8080
        environment: 
            - GRdockPC_ADDRESS=go-grpc:8080
        networks: 
            - go-grpc-net
    go-grpc:
        build: 
            context: .
            dockerfile: grpc.Dockerfile
        image: davidyap/go-2:latest
        container_name: go-grpc
        networks: 
            - go-grpc-net

networks: 
    go-grpc-net:
        driver: bridge