// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.2
// source: rpc/math/math.proto

package math

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlusParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A float32 `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B float32 `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *PlusParam) Reset() {
	*x = PlusParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_math_math_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlusParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlusParam) ProtoMessage() {}

func (x *PlusParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_math_math_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlusParam.ProtoReflect.Descriptor instead.
func (*PlusParam) Descriptor() ([]byte, []int) {
	return file_rpc_math_math_proto_rawDescGZIP(), []int{0}
}

func (x *PlusParam) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *PlusParam) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

type PlusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float32 `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PlusResponse) Reset() {
	*x = PlusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_math_math_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlusResponse) ProtoMessage() {}

func (x *PlusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_math_math_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlusResponse.ProtoReflect.Descriptor instead.
func (*PlusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_math_math_proto_rawDescGZIP(), []int{1}
}

func (x *PlusResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_rpc_math_math_proto protoreflect.FileDescriptor

var file_rpc_math_math_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x09, 0x50, 0x6c, 0x75, 0x73, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x61,
	0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x62, 0x22, 0x26,
	0x0a, 0x0c, 0x50, 0x6c, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x30, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x68, 0x47, 0x75,
	0x69, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x50, 0x6c, 0x75, 0x73, 0x12, 0x0a, 0x2e, 0x50, 0x6c,
	0x75, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x0d, 0x2e, 0x50, 0x6c, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x72, 0x70,
	0x63, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_math_math_proto_rawDescOnce sync.Once
	file_rpc_math_math_proto_rawDescData = file_rpc_math_math_proto_rawDesc
)

func file_rpc_math_math_proto_rawDescGZIP() []byte {
	file_rpc_math_math_proto_rawDescOnce.Do(func() {
		file_rpc_math_math_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_math_math_proto_rawDescData)
	})
	return file_rpc_math_math_proto_rawDescData
}

var file_rpc_math_math_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_math_math_proto_goTypes = []interface{}{
	(*PlusParam)(nil),    // 0: PlusParam
	(*PlusResponse)(nil), // 1: PlusResponse
}
var file_rpc_math_math_proto_depIdxs = []int32{
	0, // 0: MathGuide.Plus:input_type -> PlusParam
	1, // 1: MathGuide.Plus:output_type -> PlusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_math_math_proto_init() }
func file_rpc_math_math_proto_init() {
	if File_rpc_math_math_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_math_math_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlusParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_math_math_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_math_math_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_math_math_proto_goTypes,
		DependencyIndexes: file_rpc_math_math_proto_depIdxs,
		MessageInfos:      file_rpc_math_math_proto_msgTypes,
	}.Build()
	File_rpc_math_math_proto = out.File
	file_rpc_math_math_proto_rawDesc = nil
	file_rpc_math_math_proto_goTypes = nil
	file_rpc_math_math_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MathGuideClient is the client API for MathGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathGuideClient interface {
	Plus(ctx context.Context, in *PlusParam, opts ...grpc.CallOption) (*PlusResponse, error)
}

type mathGuideClient struct {
	cc grpc.ClientConnInterface
}

func NewMathGuideClient(cc grpc.ClientConnInterface) MathGuideClient {
	return &mathGuideClient{cc}
}

func (c *mathGuideClient) Plus(ctx context.Context, in *PlusParam, opts ...grpc.CallOption) (*PlusResponse, error) {
	out := new(PlusResponse)
	err := c.cc.Invoke(ctx, "/MathGuide/Plus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathGuideServer is the server API for MathGuide service.
type MathGuideServer interface {
	Plus(context.Context, *PlusParam) (*PlusResponse, error)
}

// UnimplementedMathGuideServer can be embedded to have forward compatible implementations.
type UnimplementedMathGuideServer struct {
}

func (*UnimplementedMathGuideServer) Plus(context.Context, *PlusParam) (*PlusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Plus not implemented")
}

func RegisterMathGuideServer(s *grpc.Server, srv MathGuideServer) {
	s.RegisterService(&_MathGuide_serviceDesc, srv)
}

func _MathGuide_Plus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlusParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathGuideServer).Plus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathGuide/Plus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathGuideServer).Plus(ctx, req.(*PlusParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _MathGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MathGuide",
	HandlerType: (*MathGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plus",
			Handler:    _MathGuide_Plus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/math/math.proto",
}
